spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tian2
    username: root
    password: 123456


  mail:
    host: smtp.qq.com
    port: 587
    username: 1453419426@qq.com      # 你的邮箱
    password: tkahlwwppdksbadh       # QQ 邮箱授权码（非密码）
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  logging:
    level:
      org.springframework.jdbc.core: DEBUG
      org.hibernate: DEBUG

  redis:
    host: 127.0.0.1
    port: 6379

  redisson:
    config: classpath:redisson.yml





#  spring:
#    rabbitmq:
#      host: localhost
#      port: 15672
#      username: guest
#      password: guest




